mcd89/mcd-UPYOG

- business-services/egov-hrms/src/main/java/org/egov/hrms/model/Jurisdiction.java
- business-services/egov-hrms/src/main/java/org/egov/hrms/repository/EmployeeQueries.java
- business-services/egov-hrms/src/main/java/org/egov/hrms/repository/EmployeeRowMapper.java
- core-services/egov-persister/src/main/resources/hrms-employee-persister.yml
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/jurisdiction.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EmployeeDetails.js
Hrms zone wise user create, search and zone Dropdown.
> hrms zone changes

- business-services/egov-hrms/src/main/java/org/egov/hrms/service/DefaultUserService.java
- business-services/egov-hrms/src/main/java/org/egov/hrms/web/controller/EmployeeController.java
- business-services/egov-hrms/src/main/resources/db/migration/main/V20250130120650__alter_jurisdiction_add_zone_ddl.sql
- core-services/egov-persister/src/main/resources/hrms-employee-persister.yml
- core-services/egov-user/src/main/java/org/egov/user/domain/model/Action.java
- core-services/egov-user/src/main/java/org/egov/user/domain/model/Address.java
- core-services/egov-user/src/main/java/org/egov/user/domain/model/Role.java
- core-services/egov-user/src/main/java/org/egov/user/domain/model/User.java
- core-services/egov-user/src/main/java/org/egov/user/domain/model/UserSearchCriteria.java
- core-services/egov-user/src/main/java/org/egov/user/web/contract/RoleRequest.java
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EmployeeDetails.js
added zone wise user updation done
> employee-updation working

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/services/atoms/urls.js
update urls for hrms-service, remove localhost urls in hrms
> update urls.js file for hrms

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/services/atoms/urls.js
> Main to master push

- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/jurisdiction.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EmployeeDetails.js
> zone updated

- frontend/micro-ui/web/package.json
Workspace added in package.json file
> workspace added

- frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
- frontend/micro-ui/web/micro-ui-internals/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/jurisdiction.js
- frontend/micro-ui/web/package.json
micro-ui updated for hrms 
updated files :- 
Jurisdiction.js
EmployeeDetails.js
TopBar.js
login.js
> HRMS micror-ui updated 

- frontend/micro-ui/web/micro-ui-internals/.gitignore
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/jurisdiction.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EmployeeDetails.js
Updated Jurisdiction code and login
EmployeeDetails and remove css file from gitignore
> hrms updated

- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
> login page updated

- municipal-services/asset-services/src/main/resources/application.properties
I have updated the domain URL in application.properties file
> updated application.properties

- frontend/micro-ui/web/micro-ui-internals/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
- frontend/micro-ui/web/package.json
update workspace on packapge.json file
> update workspace & topbar

- frontend/micro-ui/web/micro-ui-internals/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/ads/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/asset/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/bills/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/chb/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/common/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/commonPt/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/dss/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/engagement/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/ew/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/fsm/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/mCollect/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/noc/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/pgr/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/pt/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/ptr/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/receipts/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/reports/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/sv/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/tl/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/vendor/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/ws/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/wt/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/react-components/package.json
- frontend/micro-ui/web/package.json
update react-component version
> update react-component version 1.2.13

- frontend/micro-ui/web/micro-ui-internals/example/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/jurisdiction.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EditEmployee/EditForm.js
- frontend/micro-ui/web/package.json
update hrms npm version 1.2.5, topbar updated and localization done.
> update hrms topbar

- frontend/micro-ui/web/micro-ui-internals/example/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/src/Module.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/src/components/financecard.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/src/pages/index.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/src/utils/RedirectToFinanceHome.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/src/utils/RedirectToFinanceInbox.js
- frontend/micro-ui/web/package.json
update finance card links to redirect mono-ui
> update financecard links

- frontend/micro-ui/web/micro-ui-internals/example/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/src/utils/RedirectToFinanceHome.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/finance/src/utils/RedirectToFinanceInbox.js
- frontend/micro-ui/web/package.json
> finance card updated

- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
Topbar updated, ulbgrade & tenant are combine together and set a single localization
> topbar updated

- build/build-config.yml
I have updated the configuration in build-config.yaml, I have added the home service for the build and deployment.
> updated build-config.yaml

- municipal-services/home/pom.xml
- municipal-services/home/src/main/resources/application.properties
- municipal-services/home/src/main/resources/db/migration/V1__init.sql
> flyway issue resolved

- municipal-services/home/src/main/java/com/mcd/home/config/MvcConfig.java
- municipal-services/home/src/main/resources/application.properties
> Assets also allow with **

- municipal-services/home/src/main/java/com/mcd/home/controller/HomeController.java
- municipal-services/home/src/main/resources/application.properties
> url updated

- business-services/egf-instrument/src/main/java/org/egov/egf/instrument/domain/service/InstrumentService.java
- business-services/egf-instrument/src/main/resources/db/migration/seed/V20180928161817__egf_instrumentmapping_jal_amr.sql
- business-services/egf-instrument/src/main/resources/db/migration/seed/V20181010160919__egf_instrument_type_for_punjab.sql
Changes in microservices for remittance
> Changes in micro-services for remittance

- business-services/egf-instrument/src/main/resources/db/migration/seed/V20180928161817__egf_instrumentmapping_jal_amr.sql
fix: resolve Flyway checksum mismatch for migration 20180928161817
> fix: resolve Flyway checksum mismatch for migration 20180928161817

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/Header/components/AppBar/index.js
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/Header/index.js
> zone added

- frontend/finance-ui/web/finance/Dockerfile
I have updated the Dockerfile for the finance-ui
> updated dockerfile

- frontend/finance-ui/web/micro-ui-internals/example/package.json
- frontend/finance-ui/web/micro-ui-internals/example/src/index.js
- frontend/finance-ui/web/micro-ui-internals/package.json
- frontend/finance-ui/web/micro-ui-internals/packages/modules/finance2/package.json
- frontend/finance-ui/web/micro-ui-internals/packages/modules/finance2/src/Module.js
- frontend/finance-ui/web/micro-ui-internals/packages/modules/finance2/src/components/FinanceCard.js
- frontend/finance-ui/web/micro-ui-internals/packages/modules/finance2/src/components/inbox.js
- frontend/finance-ui/web/micro-ui-internals/packages/modules/finance2/src/components/test/JournalVoucher.js
- frontend/finance-ui/web/micro-ui-internals/packages/modules/finance2/src/pages/index.js
- frontend/finance-ui/web/micro-ui-internals/yarn.lock
- frontend/finance-ui/web/package.json
- frontend/finance-ui/web/yarn.lock
finance module added and show showing on finance-ui
> finance module added and card showing on finance-ui

- frontend/finance-ui/web/micro-ui-internals/example/package.json
> changes in packages.json

- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/index.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/ChangePassword/changePassword.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/LanguageSelection/index.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
footer and login background updated
> footer and login background updated on micro-ui

- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ChangeRole.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/SideBar/CitizenSideBar.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
user role list showing in topbar  of micro-ui
changes files:-
CitizenSidebar.js
TopBar.js
created file - ChangeRole.js
> user role list showing in topbar  & sidebar

- frontend/finance-ui/web/src/App.js
App.js file updated of web folder on finance-ui
> update App.js file

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/api.js
- frontend/mono-ui/web/rainmaker/packages/employee/src/modules/employee/Inbox/index.js
InvalidTokenException issue resolved in mono-ui and set digit-ui login page redirection after logout
when user get InvalidTokenException in any api call then session and localstorage is clean
> InvalidTokenException issue resolved in mono-ui

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/auth/actions.js
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/api.js
updated logout redirection on mono-ui
when user logout from mono-ui dashboard then it should be redirect to micro-ui login page
> updated logout redirection on mono-ui

- core-services/egov-user/src/main/java/org/egov/user/security/oauth2/custom/CustomAuthenticationManager.java
- core-services/egov-user/src/main/java/org/egov/user/security/oauth2/custom/authproviders/CustomAuthenticationProvider.java
> logs update in auth manager

- core-services/egov-user/src/main/java/org/egov/user/security/AuthorizationServerConfiguration.java
- core-services/egov-user/src/main/java/org/egov/user/security/oauth2/custom/CustomTokenService.java
stale token cleaning and user api error issue handled under testing
> stale token cleaning and user api error issue handled under testing

- core-services/egov-user/src/main/java/org/egov/user/security/oauth2/custom/CustomTokenService.java
stale token cleaning and user api error issue handled under testing 4
> stale token cleaning and user api error issue handled under testing 4

- core-services/egov-user/src/main/java/org/egov/user/security/oauth2/custom/CustomTokenService.java
Logs added in custom Access token service
> Logs added in custom Access token service

- core-services/egov-user/src/main/java/org/egov/user/security/CustomAuthenticationKeyGenerator.java
extract key generator class logs added
> extract key generator class logs added

- core-services/egov-user/src/main/java/org/egov/user/security/oauth2/custom/CustomTokenService.java
delete stale auth key method code cleaning done in CustomTokenService
> delete stale auth key method code cleaning done in CustomTokenService

- business-services/egov-hrms/src/main/java/org/egov/hrms/service/EmployeeService.java
> user id updated on egov-hrms

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/ActionMenu/components/index.scss
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/Header/components/UserSettings/index.scss
- frontend/mono-ui/web/rainmaker/packages/employee/public/index.html
The issue where there was a gap when the sidebar menu opened after zooming in or out of the browser window has been resolved.
> sidebar menu gap ui issues solved

- core-services/egov-user/src/main/java/org/egov/user/domain/service/TokenService.java
Connection close after the delete is handled
> Connection close after the delete is handled

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/auth/actions.js
update method name in mono-ui while logout from finance backend
> update method name

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/auth/actions.js
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/api.js
Logout API calling when token get invalid, or throw InvalidAccessToken Exception then it first logout from finance backend (calling logout api in finance) then redirect to the login page.
files changes: api.js
> logout api implement on invalidaccesstokenexception

- frontend/mono-ui/web/rainmaker/package.json
- frontend/mono-ui/web/rainmaker/packages/employee/.env
- frontend/mono-ui/web/rainmaker/packages/employee/package.json
Update employee package configurations and environment variables
> Update employee package configurations and environment variables

- core-services/egov-user/src/main/java/org/egov/user/security/AuthorizationServerConfiguration.java
user service changed reverted to handle api error
> user service changed reverted to hanlde api error

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/ActionMenu/components/index.js
Add home icon to ActionMenu for quick navigation in Digit-UI
> Add home icon to ActionMenu for quick navigation

- municipal-services/home-ui/src/main/resources/templates/index.html
> Home ui plus sign

- municipal-services/home-ui/src/main/resources/templates/index.html
mcd online website mapped on logo click
> mcd online website mapped on logo click

- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/assignment.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EditEmployee/EditForm.js
- Allowed updates to department and designation dropdowns within assignment details
- Enabled zone selection in jurisdiction section
> Allowed updates to department and designation dropdowns within assignment details and Enabled zone selection in jurisdiction section

- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/assignment.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EditEmployee/EditForm.js
- Integrated division dropdown in create employee form
- Ensured division resets automatically on zone change
- Updated edit flow to handle division selection correctly
> add division dropdown in employee create & update flow

- frontend/micro-ui/web/micro-ui-internals/example/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/assignment.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EditEmployee/EditForm.js
- frontend/micro-ui/web/package.json
- Updated HRMS module version from 1.2.5 → 1.2.6
- Enhanced Assignments component to correctly preserve division during employee update
- Added normalization step after MDMS data load to sync existing divisions with valid zone mappings
- Prevented division from being reset to null when already valid
- Implemented auto-selection of division when only one option
> Update HRMS module version to 1.2.6 and enhance assignment component for division handling in Micro-UI

- frontend/micro-ui/web/micro-ui-internals/example/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/assignment.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EditEmployee/EditForm.js
- frontend/micro-ui/web/package.json
Update HRMS module version to 1.2.8 and refactor assignment component
> Update HRMS module version to 1.2.8 and refactor assignment component

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/api.js
Enhance error handling in httpRequest to manage token invalidation and improve user redirection
> Enhance error handling in httpRequest to manage token invalidation and improve user redirection

- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/ActionMenu/components/index.js
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/ActionMenu/components/index.scss
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/ActionMenu/index.scss
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/Header/components/UserSettings/index.js
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/Header/components/UserSettings/index.scss
- frontend/mono-ui/web/rainmaker/dev-packages/egov-ui-kit-dev/src/components/Label/index.scss
Sidebar: Update rendering to skip Finance root and directly display its child menus using getSubmenuItems("Finance")
> Refactor ActionMenu component and improve styling for better UI consistency

- business-services/egov-hrms/src/main/java/org/egov/hrms/model/Employee.java
Fixed the issue Username will be trimed if any space added on start and at end
> Update Employee.java Fixed the issue Username will be trimed if any space added on start and at end

- municipal-services/home-ui/src/main/java/com/mcd/home/controller/HomeController.java
- municipal-services/home-ui/src/main/resources/templates/expenditure_table.html
- municipal-services/home-ui/src/main/resources/templates/income_table.html
- municipal-services/home-ui/src/main/resources/templates/index.html
home ui updated - income and expenditure account head mapping old vs new pages added
> home ui updated - income and expenditure account head mapping old vs new pages added

- frontend/micro-ui/web/micro-ui-internals/example/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/inbox/DesktopInbox.js
- frontend/micro-ui/web/package.json
update hrms module version to 1.2.11 and update zone translation key
> update hrms module version to 1.2.11 and update zone translation key

- frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/login.scss
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
hide the city on topbar and add the width on login page
> hide the city on topbar
